_target_: newsreclib.models.general_rec.caum_module.CAUMModule

# training strategy
dual_loss_training: False
dual_loss_coef: null
loss: "cross_entropy_loss"
late_fusion: False
temperature: None

# news encoder
dataset_attributes: ${data.dataset_attributes}
attributes2encode: ["title", "category", "title_entities"]
use_plm: False
use_entities: True

# text encoder
pretrained_word_embeddings_path: null
pretrained_entity_embeddings_path: null
plm_model: null
frozen_layers: null
text_embed_dim: 300
text_num_heads: 20
categ_embed_dim: 100
news_embed_dim: 400
entity_embed_dim: 100
entity_num_heads: 20
query_dim: 200
dropout_probability: 0.2

# user encoder
user_vector_dim: 400
num_filters: 400
dense_att_hidden_dim1: 400
dense_att_hidden_dim2: 256

# outputs
outputs:
  train: ["preds", "targets", "cand_news_size"]
  val: ["preds", "targets", "cand_news_size"]
  test:
    [
      "preds",
      "targets",
      "cand_news_size",
      "hist_news_size",
      "target_categories",
      "target_sentiments",
      "hist_categories",
      "hist_sentiments",
      "user_ids",
      "cand_news_ids",
    ]

# evaluation
top_k_list: [5, 10]
num_categ_classes: 18
num_sent_classes: 3
save_recs: False
recs_fpath: "${paths.output_dir}/recommendations.json"

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001

scheduler: null
