_target_: newsreclib.models.general_rec.npa_module.NPAModule

# training strategy
dual_loss_training: False
dual_loss_coef: null
loss: "cross_entropy_loss"
late_fusion: False
temperature: None

# news encoder
pretrained_embeddings_path: null
text_embed_dim: 300
user_embed_dim: 50
num_users: 45214
num_filters: 400
window_size: 3
word_pref_query_dim: 200
news_pref_query_dim: 200
dropout_probability: 0.2

# outputs
outputs:
  train: ["preds", "targets", "cand_news_size"]
  val: ["preds", "targets", "cand_news_size"]
  test:
    [
      "preds",
      "targets",
      "cand_news_size",
      "hist_news_size",
      "target_categories",
      "target_sentiments",
      "hist_categories",
      "hist_sentiments",
      "user_ids",
      "cand_news_ids",
    ]

# evaluation
top_k_list: [5, 10]
num_categ_classes: 18
num_sent_classes: 3
save_recs: False
recs_fpath: "${paths.output_dir}/recommendations.json"

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001

scheduler: null
